# Generated by Django 3.2.25 on 2025-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
