# Generated by Django 3.2.25 on 2025-08-19 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_processedimage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
